#!/usr/bin/env bash
source "$(dirname "$0")/helper.bash"

# --- Core Logic ---

# Left click: toggle notification state
if [ "$BLOCK_BUTTON" -eq 1 ] 2>/dev/null; then
  notif-toggle
fi

if [ "$(dunstctl is-paused)" = true ]; then
  echo "󰂛"
  echo "󰂛"
  echo "$COLOR_LGRAY"
else
  echo "󰂚"
  echo "󰂚"
  echo "$COLOR_WHITE"
fi
