#!/usr/bin/env bash
source "$(dirname "$0")/helper.bash"

# --- Environment Variables ---

AUDIO_MED_THRESH=${AUDIO_MED_THRESH:-50}
AUDIO_LOW_THRESH=${AUDIO_LOW_THRESH:-0}

# --- Core Logic ---

query_vol() {
  pactl get-sink-volume @DEFAULT_SINK@ 2>/dev/null |
    grep -oP '\d+%' |
    head -1 |
    tr -d '%'
}

query_mute() {
  pactl get-sink-mute @DEFAULT_SINK@ 2>/dev/null | grep -oP 'yes|no'
}

case "$BLOCK_BUTTON" in
  1) pavucontrol & ;;
  3) vol mute ;;
  4) vol up ;;
  5) vol down ;;
esac

vol=$(query_vol)
muted=$(query_mute)

if [[ -z "$vol" ]] ; then
  echo "Sound inactive"
  echo ""
  echo "#808080"
  exit 0
fi

if [[ $muted =~ "no" ]] ; then
  icon=""
  [[ $vol -le $AUDIO_MED_THRESH ]] && icon=""
  [[ $vol -le $AUDIO_LOW_THRESH ]] && icon=""
  color="#ffffff"
else
  icon=""
  color="#a0a0a0"
fi

echo "${icon} $(printf '%3d' "$vol")%"
echo "${icon}"
echo "$color"
