" Vundle
set nocompatible " be iMproved, required for Vundle
filetype off     " required for Vundle

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'

" Plugins
" Code commenting out
Plugin 'scrooloose/nerdcommenter'
" Code completion
Plugin 'ycm-core/YouCompleteMe'
" Hex editing
Plugin 'fidian/hexmode'
" Syntax highlighting
Plugin 's3rvac/vim-syntax-retdecdsm'
" Code linting
Plugin 'tjdevries/overlength.vim'
" LaTeX
Plugin 'lervag/vimtex'
" NerdFonts
Plugin 'ryanoasis/vim-devicons'
" Status bar
Plugin 'itchyny/lightline.vim'
" File browsing
Plugin 'preservim/nerdtree'

" All plugins must be added before the following line
call vundle#end()
filetype plugin indent on
" End Vundle

" Variable Settings
" Encoding
set encoding=UTF-8

" Line Settings
set lbr
set number

" Spell Check
set spelllang=en
set spell

" Leader Settings
let mapleader = ","

" Backup Settings
set backupdir=~/.vim_backup

" Tab Width
" On pressing tab, insert 2 spaces
set expandtab
" show existing tab with 2 spaces width
set tabstop=2
set softtabstop=2
" when indenting with '>', use 2 spaces width
set shiftwidth=2

" Whitespace Visibility
" Show trailing whitespace and eol
set listchars=trail:~,tab:\ \ 
" Set visible
set list

" Tex
" Prevents vim from thinking a tex file is plaintex
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'

" Order and usage requested by vim-tex
filetype plugin indent on
syntax on

" Lightline
set laststatus=2
set noshowmode
"let g:lightline = {
      "\ 'colorscheme': 'medic_chalk',
      "\ }

