" Vundle
set nocompatible " be iMproved, required for Vundle
filetype off     " required for Vundle

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'

" Plugins
" Colors
Plugin 'ParamagicDev/vim-medic_chalk'
" Code Commenting Out
Plugin 'scrooloose/nerdcommenter'
" Code Completion
Plugin 'ycm-core/YouCompleteMe'
" Hex Editing
Plugin 'fidian/hexmode'
" Syntax Highlighting
Plugin 's3rvac/vim-syntax-retdecdsm'
" Code linting
Plugin 'tjdevries/overlength.vim'
" LaTeX
Plugin 'lervag/vimtex'

" All plugins must be added before the following line
call vundle#end()
filetype plugin indent on
" End Vundle

" Variable Settings
" Colors
colorscheme medic_chalk

" Line Settings
set lbr
set number

" Spell Check
set spelllang=en
set spell

" Leader Settings
let mapleader = ","

" Backup Settings
set backupdir=~/.vim_backup

" Tab Width
" On pressing tab, insert 2 spaces
set expandtab
" show existing tab with 2 spaces width
set tabstop=2
set softtabstop=2
" when indenting with '>', use 2 spaces width
set shiftwidth=2

" Whitespace Visibility
" Show trailing whitespace and eol
set listchars=trail:~,eol:¬
" Set visible
set list

" Tex
" Prevents vim from thinking a tex file is plaintex
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'

" Order and usage requested by vim-tex
filetype plugin indent on
syntax on

