set encoding=utf-8
" Vundle
set nocompatible " required for Vundle
filetype off     " required for Vundle

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'

" Plugins
" Code commenting out
Plugin 'scrooloose/nerdcommenter'
" Code completion
Plugin 'ycm-core/YouCompleteMe'
Plugin 'Vimjas/vim-python-pep8-indent'
" Hex editing
Plugin 'fidian/hexmode'
" Syntax highlighting
Plugin 's3rvac/vim-syntax-retdecdsm'
" Code linting
Plugin 'dense-analysis/ale'
Plugin 'tjdevries/overlength.vim'
" LaTeX
Plugin 'lervag/vimtex'
" Markdown
Plugin 'JamshedVesuna/vim-markdown-preview'
" NerdFonts
Plugin 'ryanoasis/vim-devicons'
" Status bar
Plugin 'itchyny/lightline.vim'
" File browsing
Plugin 'preservim/nerdtree'
" Git
Plugin 'airblade/vim-gitgutter'

" All plugins must be added before the following line
call vundle#end()
filetype plugin indent on
" End Vundle

" Line Settings
set lbr
set number

" Spell Check
set spelllang=en
set spell

" Leader Settings
let mapleader = ","
set showcmd

" Backup Settings
set backupdir=~/.vim_backup

" Bring search results to mid-screen
noremap n nzz
noremap N Nzz

" Tab Width
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" Folding
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=2

" Whitespace Visibility
" Show trailing whitespace and eol
set listchars=trail:·,tab:»·
set list

" Markdown
let vim_markdown_peview_toggle = 2

" Tex
" Prevents vim from thinking a tex file is plaintex
let g:tex_flavor = 'latex'
let g:vimtex_view_method = 'zathura'
" Order and usage requested by vim-tex
filetype plugin indent on
syntax on

" Lightline
set laststatus=2
set noshowmode
let g:lightline = {
	\ 'colorscheme': 'default',
	\ }

" NERDTree
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>
" Start NERDTree and put the cursor back in the other window
autocmd VimEnter * NERDTree | wincmd p
" Exit Vim if NERDTree is the only window left
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1
    \ && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

" Gitgutter
set updatetime=100 " Update every 100 ms(also controls swap file)
let b:ale_linters = {
			\	'python': ['pylint'],
			\}
let b:ale_fixers = {
			\	'*': ['remove_trailing_lines', 'trim_whitespace'],
			\	'python': ['yapf'],
			\}
let g:ale_fix_on_save = 1
